title: My Blog
email: your-email@example.com
description: >- 
  This is my blog.
baseurl: "" 
url: "https://highbestcoder.github.io/blog" 
twitter_username: yourtwitter
github_username:  HighBestCoder
