title: HighBestCoder's Blog
description: This is my personal blog.
baseurl: "https://highbestcoder.github.io/blog"
url: "https://highbestcoder.github.io/blog" 

# 主题特定配置
gitbook:
  search: true
  download: ["pdf", "epub"]
  github:
    url: https://github.com/HighBestCoder/blog
  logo: /assets/images/logo.png
  favicon: /assets/images/favicon.ico
